### ISSUE TITLE
python

### ISSUE THREAD

**Issue by beyzatuzcu** [beyzatuzcu/python_calismalari#1]
c=27.5
if (int(c)==c):
    print(f"{int(c)} is equal to {c}")
else:
    print(f"{int(c)} is not equal to{c}")

name="aaa"
def func():
    global name
    name="bb"
func()
print(name)

list1=[1,5,7,2,4,12]
result_list=[]
def lets_add():
    for i in list1:
        if i %2==0:
            result_list.append(i)
lets_add()
print(result_list)

person_list={
            "a":34,
            "b":47,
            "c": 28
            }
sum=0
for x in person_list.values():
    if x>28:
        sum+=x
print(sum)

**Comment by beyzatuzcu** [comment]
python örnek çalışmalar

**Comment by Sd-Shiivam** [comment]
python is a case sensitive language due to which we have to give proper indents like below --
```
c=27.5
if (int(c)==c):
    print(f"{int(c)} is equal to {c}")
else:
    print(f"{int(c)} is not equal to{c}")

name="aaa"
def func():
    global name
    name="bb"
func()
print(name)

list1=[1,5,7,2,4,12]
result_list=[]
def lets_add():
    for i in list1:
        if i %2==0:
            result_list.append(i)
lets_add()
print(result_list)

person_list={
            "a":34,
            "b":47,
            "c": 28
            }
sum=0
for x in person_list.values():
    if x>28:
        sum+=x
print(sum)
```

**Comment by theocean123** [comment]
Less the imput

**Comment by beyzatuzcu** [comment]
Teşekkürler.
